import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
 import { ProgressBar, ProgressBarProvider } from "react-transition-progress";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <ProgressBarProvider>
              <ProgressBar className="fixed z-50 h-10 shadow-lg shadow-sky-500/20 bg-red-500 top-0" />
              {children}
            </ProgressBarProvider>
      </body>
    </html>
  );
}
